name: 'Show Comments in Actions'
inputs:
  json_file:
    description: 'Where to find the json output of the comments'
    required: true
    default: 'comments.json'
  
  vt_api_key:
    description: 'virusTotal API token'
    required: true  
    
  repo_name:
    description: 'repo name'
    required: true  

  repo_owner:
    description: 'repo_owner'
    required: true  

runs:
  using: 'node12'
  main: 'dist/index.js'