name: 'Get Github Actions Logs'
inputs:
  json_file:
    description: 'Where to find the json output of the comments'
    required: true
    default: 'comments.json'

  token:
    description: 'GitHub token'
    default: ${{github.token}}
    required: true

  repo_owner:
    description: 'name of the repo owner to collect logs'
    required: true
  
  repo_name:
    description: 'name of the repo to collect logs'
    required: true
  
  
runs:
  using: 'node12'
  main: 'dist/index.js'