name: Get Github Actions Logs

on:
  push:
    branches:
      - "main" 


jobs:
  Get-Github-Actions-Logs: 
    runs-on: ubuntu-latest 
    name: Get Github Actions Logs

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Logs
        uses: ./
        with: \
          repo_owner: "xjin-splunk",
          repo_name: "get_github_actions_logs"


